services:
  mariadb:
    image: mariadb:11.6.2
    container_name: ${iDB_service_container_name}
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${iDB_service_mysql_root_password}
    network_mode: ${iDB_service_network_mode}
    ports:
      - ${iDB_service_port}:3306
    volumes:
      - ${iDB_service_config_path}/my.cnf:/etc/mysql/my.cnf
      - ${iDB_service_data_path}:/var/lib/mysql
      - ${iDB_service_log_path}:/var/log/mysql
      - ${iDB_service_cert_path}:/data/cert
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --explicit_defaults_for_timestamp=1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      net.idb.type: "app"
      net.idb.name: "mariadb"
      net.idb.version: "11.6"
      net.idb.update_version: "2"
      net.idb.panel: "mysqlmanager"